#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Colors
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Emojis
CHECK_MARK='\xE2\x9C\x85'
HOURGLASS='\xE2\x8C\x9B'
SPARKLES='\xE2\x9C\xa8'
GREEN='\033[0;32m'

# Step 6: Validate commit message
printf "\n${HOURGLASS} ${YELLOW}Validating commit message. Please wait...${NC}\n"
npx --no -- commitlint --edit ${1}
echo "${CHECK_MARK} ${GREEN}Commit message validation complete.${NC}"

# Summary
echo "\n${SPARKLES} ${GREEN}All checks passed successfully!${NC}\n"
